# Generated by Django 5.1.3 on 2024-11-29 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panenan',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='petani',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='tanaman',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='panenan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petani',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanaman',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
